core/urls.py
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from account.views import Register, RegisterInvite, login_page
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

# for private
import private_storage.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # Media file
    path('private-media/', include(private_storage.urls)),


]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    # AUTH
    path('register', Register, name='register'),
    path('login', login_page, name='login'),
    path('logout/', auth_views.LogoutView.as_view(),
         {'next_page': 'main:start'}, name='logout'),

    # PW reset
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password_reset/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset/password_reset_form.html'), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),


    # Invite
    path('register/invite/<token>', RegisterInvite, name='register_invite'),

    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('order/', include('order.urls')),
    path('client/', include('client.urls')),
    path('project/', include('project.urls')),
    path('notification/', include('notification.urls')),
    path('', include('main.urls')),
    prefix_default_language=False
)


# Error Handling
handler400 = 'main.views.handler_400_view'
handler403 = 'main.views.handler_403_view'
handler404 = 'main.views.handler_404_view'
handler500 = 'main.views.handler_500_view'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.project_index_view, name='project_index'),
    path('create/<client_id>/<product_id>/<order_id>',
         views.project_create_view, name='project_create'),
    path('create/admin', views.project_create_admin_view,
         name='project_create_admin'),
    path('<int:id>', views.project_detail_view, name='project_detail'),
    path('edit/<int:project_id>', views.project_edit_view, name='project_edit'),
    path('close/<int:project_id>', views.project_close_view, name='project_close'),
    path('archive/<int:project_id>', views.project_archive_view, name='project_archive'),
    path('unarchive/<int:project_id>', views.project_unarchive_view, name='project_unarchive'),


    # Team
    path('<int:project_id>/team', views.project_team_index_view,
         name='project_team_index'),
    path('<int:project_id>/team/create',
         views.project_team_create_view, name='project_team_create'),
    path('<int:project_id>/team-book/create',
         views.project_team_book_create_view, name='project_team_book_create'),
    path('<int:project_id>/team/edit/<int:id>',
         views.project_team_edit_view, name='project_team_edit'),
    path('<int:project_id>/project_team_invite',
         views.project_team_invite_view, name='project_team_invite'),
     path('<int:project_id>/team/invite/delete/<int:id>',
         views.project_team_invite_delete_view, name='project_team_invite_delete'),

     # Document
     
    path('<int:project_id>/document', views.project_document_index_view,
         name='project_document_index'),
    path('<int:project_id>/document/create',
         views.project_document_create_view, name='project_document_create'),
     path('<int:project_id>/document/detail/<int:id>',
         views.project_document_detail_view, name='project_document_detail'),
    path('<int:project_id>/document/edit/<int:id>',
         views.project_document_edit_view, name='project_document_edit'),
     path('<int:project_id>/document/pdf/generate/<int:id>',
         views.GeneratePdf.as_view(), name='project_document_pdf_generate'),
     path('<int:project_id>/document/delete/<int:id>',
         views.project_document_delete_view, name='project_document_delete'),

     

    # Note
    path('<int:project_id>/note', views.project_note_index_view,
         name='project_note_index'),
    path('<int:project_id>/note/create',
         views.project_note_create_view, name='project_note_create'),
    path('<int:project_id>/note/edit/<int:id>',
         views.project_note_edit_view, name='project_note_edit'),
    path('<int:project_id>/note/<int:id>/file/create',
         views.project_note_create_file_view, name='project_note_create_file'),

    # Meet
    path('<int:project_id>/meet', views.project_meet_index_view,
         name='project_meet_index'),
    path('<int:project_id>/meet/create',
         views.project_meet_create_view, name='project_meet_create'),
    path('<int:project_id>/meet/<int:id>',
         views.project_meet_detail_view, name='project_meet_detail'),
    path('<int:project_id>/meet/<int:id>/file/create',
         views.project_meet_create_file_view, name='project_meet_create_file'),
     path('<int:project_id>/meet/<int:id>/edit',
         views.project_meet_edit_view, name='project_meet_edit'),
     path('<int:project_id>/meet/<int:id>/invite',
         views.project_meet_invite_view, name='project_meet_invite'),
    path('<int:project_id>/meet/<int:id>/note/create',
         views.project_note_meet_create_view, name='project_note_meet_create'),
     path('<int:project_id>/meet/delete/<int:id>',
         views.project_meet_delete_view, name='project_meet_delete'),

         
    # Task
    path('<int:project_id>/task', views.project_task_index_view,
         name='project_task_index'),
    path('<int:project_id>/task/<int:id>',
         views.project_task_detail_view, name='project_task_detail'),
    path('<int:project_id>/task/create',
         views.project_task_create_view, name='project_task_create'),
    path('<int:project_id>/task/edit/<int:id>',
         views.project_task_edit_view, name='project_task_edit'),
     path('<int:project_id>/task/responsible/<int:id>',
         views.project_task_responsible_view, name='project_task_responsible'),
    path('<int:project_id>/task/<int:id>/file/create',
         views.project_task_create_file_view, name='project_task_create_file'),
    path('<int:project_id>/task/<int:id>/note/create',
         views.project_note_task_create_view, name='project_note_task_create'),
    path('<int:project_id>/task/archive/<int:id>',
         views.project_task_archive_view, name='project_task_archive'),
     path('<int:project_id>/task/unarchive/<int:id>',
         views.project_task_unarchive_view, name='project_task_unarchive'),

    # Message
    path('<int:project_id>/message', views.project_message_index_view,
         name='project_message_index'),
    path('<int:project_id>/message/users',
         views.project_message_users_view, name='project_message_users'),
    path('<int:project_id>/message/file',
         views.project_message_files_view, name='project_message_files'),

    # File
    path('<int:project_id>/file', views.project_file_index_view,
         name='project_file_index'),
    path('<int:project_id>/file/<int:id>',
         views.project_file_detail_view, name='project_file_detail'),
    path('<int:project_id>/file/create',
         views.project_file_create_view, name='project_file_create'),
    path('<int:project_id>/file/edit/<int:id>',
         views.project_file_edit_view, name='project_file_edit'),
    path('<int:project_id>/file/archive/<int:id>',
         views.project_file_archive_view, name='project_file_archive'),
     path('<int:project_id>/file/unarchive/<int:id>',
         views.project_file_unarchive_view, name='project_file_unarchive'),
    path('<int:project_id>/file/delete/<int:id>',
         views.project_file_delete_view, name='project_file_delete'),


    # Forms
     path('<int:project_id>/form', views.project_form_index_view, name='project_form_index'),
     path('<int:project_id>/form/<int:id>', views.project_form_detail_view, name='project_form_detail'),
     path('<int:project_id>/form/create', views.project_form_create_view, name='project_form_create'),
     # Add users and edit
     path('<int:project_id>/form/duplicate/<int:id>', views.project_form_duplicate_view, name='project_form_duplicate'),
     path('<int:project_id>/form/responsible/<int:id>', views.project_form_responsible_view, name='project_form_responsible'),

    path('<int:project_id>/form/edit/<int:id>', views.project_form_edit_view, name='project_form_edit'),
    path('<int:project_id>/form/edit/participant/<int:id>', views.project_form_edit_participant_view, name='project_form_edit_participant'),
    
    path('forms', views.forms_index_view, name='forms_index'),
    path('<int:project_id>/form/<int:id>/file/create', views.project_form_create_file_view, name='project_form_create_file'),
    path('<int:project_id>/form/<int:id>/note/create', views.project_note_form_create_view, name='project_note_form_create'),

    # Activity
    path('<int:project_id>/activity', views.project_activity_index_view, name='project_activity_index'),
    path('<int:project_id>/lawyer/activity', views.project_lawyer_activity_index_view, name='project_lawyer_activity_index'),

    # Invite
    path('invite', views.invite_index_view, name='invite_index'),
    path('invite/accept/<int:project_id>', views.invite_accept_view, name='invite_accept'),
    path('invite/decline/<int:project_id>', views.invite_decline_view, name='invite_decline'),

    # Lawyer ----------------------------------------------------------------------------------------------

    # Lawyer Overview
    path('<int:project_id>/lawyer', views.project_lawyer_index_view,
         name='project_lawyer_index'),

    # Lawyer - Note
    path('<int:project_id>/lawyer/note',
         views.project_lawyer_note_index_view, name='project_lawyer_note_index'),
    path('<int:project_id>/lawyer/note/create',
         views.project_lawyer_note_create_view, name='project_lawyer_note_create'),
    #path('<int:project_id>/lawyer/note/edit/<int:id>', views.project_lawyer_note_edit_view, name='project_lawyer_note_edit'),
    path('<int:project_id>/lawyer/note/<int:id>/file/create',
         views.project_lawyer_note_create_file_view, name='project_lawyer_note_create_file'),

    # Lawyer - Task
    path('<int:project_id>/lawyer/task',
         views.project_lawyer_task_index_view, name='project_lawyer_task_index'),
    path('<int:project_id>/lawyer/task/<int:id>',
         views.project_lawyer_task_detail_view, name='project_lawyer_task_detail'),
    path('<int:project_id>/lawyer/task/create',
         views.project_lawyer_task_create_view, name='project_lawyer_task_create'),
    path('<int:project_id>/lawyer/task/edit/<int:id>',
         views.project_lawyer_task_edit_view, name='project_lawyer_task_edit'),
    path('<int:project_id>/lawyer/task/<int:id>/file/create',
         views.project_lawyer_task_create_file_view, name='project_lawyer_task_create_file'),
    path('<int:project_id>/lawyer/task/<int:id>/note/create',
         views.project_lawyer_note_task_create_view, name='project_lawyer_note_task_create'),
    path('<int:project_id>/lawyer/task/archive/<int:id>',
         views.project_lawyer_task_archive_view, name='project_lawyer_task_archive'),

    # Lawyer - Message
    path('<int:project_id>/lawyer/message',
         views.project_lawyer_message_index_view, name='project_lawyer_message_index'),
    path('<int:project_id>/lawyer/message/users',
         views.project_lawyer_message_users_view, name='project_lawyer_message_users'),
    path('<int:project_id>/lawyer/message/file',
         views.project_lawyer_message_files_view, name='project_lawyer_message_files'),

    # File

shop/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.translation import ugettext_lazy as _

PRODUCT_TYPE = (
    ('DEFAULT', _('Default')),
    ('COMPANY', _('Company')),
    ('APPOINTMENT', _('Appointment')),
)


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Currency(models.Model):
    name = models.CharField(max_length=254, null=True,)
    symbol = models.CharField(max_length=254, null=True,)
    
    def __str__(self):
        return self.symbol


class Tax(models.Model):
    name = models.CharField(max_length=254)
    rate = models.PositiveIntegerField()
    
    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=254)
    slug = models.SlugField(max_length=254)
    image = models.ImageField(blank=True)
    short_description = models.TextField(blank=True)
    description = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    calendar = models.BooleanField(default=False)
    video_url = models.CharField(max_length=254, null=True, blank=True)
    start_time_hour = models.IntegerField(default=1, null=True, blank=True, validators=[
                                          MaxValueValidator(24), MinValueValidator(1)])
    start_time_min = models.IntegerField(default=1, null=True, blank=True, validators=[
                                         MaxValueValidator(59), MinValueValidator(0)])
    end_time_hour = models.IntegerField(default=1, null=True, blank=True, validators=[
                                        MaxValueValidator(24), MinValueValidator(1)])
    end_time_min = models.IntegerField(default=1, null=True, blank=True, validators=[
                                       MaxValueValidator(59), MinValueValidator(0)])
    duration = models.IntegerField(default=1, null=True, blank=True)
    available = models.BooleanField(default=True)
    label = models.CharField(max_length=254, blank=True, null=True)
    tax = models.ForeignKey(Tax, related_name='tax_product', blank=True, null=True, on_delete=models.CASCADE)
    currency = models.ForeignKey(Currency, related_name='currency_product', blank=True, null=True, on_delete=models.CASCADE)
    comment = models.BooleanField(default=False)
    # Ez mutatja meg majd hogy egyszerű projektről van szó vagy cégalapitás -- sablonizálásnál fontos
    type = models.CharField(choices=PRODUCT_TYPE,
                            max_length=254, default='DEFAULT')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def brutto_price(self):
        if self.tax:
            return round(self.price * (1 + (self.tax.rate / 100)))
        else:
            return int(self.price)

project/templates/project/close.html
{% extends "base_project.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}
{% trans "Close case" %}
{% endblock %}


{% block content %}


<div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                <div class="nk-block">

                    <div class="nk-block-head">
                        <div class="nk-block-between g-3">
                            <div class="nk-block-head-content">
                                <h4 class="nk-block-title page-title">{% trans "Close case" %}</h4>
                                <div class="nk-block-des text-soft">
                                    <p>You have total 937 invoices.</p>
                                </div>
                            </div>
                            <div class="nk-block-head-content">
                                <a href="{% url 'project:project_index' %}"
                                    class="btn btn-outline-light bg-white d-none d-sm-inline-flex"><em
                                        class="icon ni ni-arrow-left"></em><span>Back</span></a>
                                <a href="{% url 'project:project_index' %}" class="btn btn-icon btn-outline-light bg-white d-inline-flex
                                        d-sm-none"><em class="icon ni ni-arrow-left"></em></a>
                            </div>
                        </div>
                    </div>

                    <div class="card card-preview">
                        <div class="card-inner">
                            <div class="preview-block" id="form">

                                <form method="post">
                                    {% csrf_token %}
                                    {{ form|crispy }}

                                    <button type="submit" id="btn-save" class="btn btn-primary">
                                        {% trans "Close case"%}
                                    </button>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- content @e -->


<script>
    const form = document.getElementById('form');
    const btnSave = document.getElementById('btn-save')

    form.addEventListener('submit', function () {

        btnSave.innerHTML += ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> <span> </span>'
        btnSave.setAttribute("disabled", "true")
    });
</script>

{% endblock %}

project/templates/project/detail.html
{% extends "base_project.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block title %}
{% trans "Case details" %}: {{project.name}}
{% endblock %}


{% block content %}



<div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                {% include 'section/project_header.html' %}
                <div class="nk-block">
                    <div class="card shadow-none">
                        <div class="card-content">
                            {% include 'section/project_navbar.html' %}
                            <div class="card-inner d-lg-none">
                                <div class="nk-block">

                                    <div class="nk-block-head nk-block-head-line">
                                        <h6 class="title overline-title text-base">{% trans "Information" %}</h6>
                                    </div>
                                    <div class="profile-ud-list">
                                        <div class="profile-ud-item">
                                            <div class="profile-ud wider">
                                                <span class="profile-ud-label">

                                                    {% trans "Name"%}

                                                </span>
                                                <span class="profile-ud-value">{{project.name}}</span>
                                            </div>
                                        </div>
                                        <div class="profile-ud-item">
                                            <div class="profile-ud wider">
                                                <span class="profile-ud-label">
                                                    {% trans "Client" %}
                                                </span>
                                                <span class="profile-ud-value">{{project.client}}
                                                </span>
                                            </div>
                                        </div>
                                        <div class="profile-ud-item">
                                            <div class="profile-ud wider">
                                                <span class="profile-ud-label">
                                                    {% trans "Created at" %}
                                                </span>
                                                <span class="profile-ud-value">{{project.created_at}}</span>
                                            </div>
                                        </div>
                                        <div class="profile-ud-item">
                                            <div class="profile-ud wider">
                                                <span class="profile-ud-label">
                                                    {% trans "Type of client" %}
                                                </span>
                                                <span
                                                    class="profile-ud-value">{{project.client.get_type_display}}</span>
                                            </div>
                                        </div>

                                    </div>
                                
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="nk-content">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                <!--  Help box start -->
                <div class="nk-block">

                    <div class="card">
                        <div class="card-aside-wrap">
                            <div class="card-content">

                                <div class="card-inner">
                                    <div class="nk-block-head">
                                        <div class="nk-block-between g-3">
                                            <div class="nk-block-head-content">
                                                <h3 class="nk-block-title page-title">{% trans "Quick" %} <strong
                                                        class="text-primary small">{% trans "Help" %}</strong></h3>
                                            </div>
                                        </div>
                                    </div>
                                    <p style="margin-bottom: 30px;">{% blocktranslate %}New to Legisly? You may have a number of questions, we have tried to gather the most common ones below. If you need further assistance, please visit our Knowledge Base.
                                        {% endblocktranslate %}
                                        <a href="http://help.legisly.com" class="btn btn-sm btn-primary" style="float: right;">{% blocktranslate %}Knowledge Base
                                            {% endblocktranslate %}</a>
                                    </p>
                                    <div class="row g-gs">
                                        <div class="col-lg-4">
                                            <div class="card">
                                                <div class="card-header border-bottom"><em class="icon ni ni-info"></em>&nbsp;{% blocktranslate %}Tasks
                                                    {% endblocktranslate %}</div>
                                                <div class="card-inner">
                                                    <h5 class="card-title"><em class="icon ni ni-list-check"></em>&nbsp;{% blocktranslate %}You have tasks to do!
                                                        {% endblocktranslate %}</h5>
                                                    <p class="card-text">{% blocktranslate %}In some cases we need your assistance. Want to delegate some task? Invite team members and ask some favor!
                                                        {% endblocktranslate %}</p><a href="{% url 'project:project_task_index' project.id %}"
                                                        class="btn btn-primary">{% blocktranslate %}Task management
                                                        {% endblocktranslate %}</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="card">
                                                <div class="card-header border-bottom"><em class="icon ni ni-info"></em>&nbsp;{% blocktranslate %}Forms
                                                    {% endblocktranslate %}</div>
                                                <div class="card-inner">
                                                    <h5 class="card-title"><em class="icon ni ni-folder"></em>&nbsp;{% blocktranslate %}Fill the forms!
                                                        {% endblocktranslate %}</h5>
                                                    <p class="card-text">{% blocktranslate %}We need information to solve your case. Please pay attention to fill all the forms!
                                                        {% endblocktranslate %}</p><a href="{% url 'project:project_form_index' project.id %}"
                                                        class="btn btn-primary">{% blocktranslate %}Form management
                                                        {% endblocktranslate %}</a>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="col-lg-4">
                                            <div class="card">
                                                <div class="card-header border-bottom"><em class="icon ni ni-info"></em>&nbsp;{% blocktranslate %}Team
                                                    management
                                                    {% endblocktranslate %}</div>
                                                <div class="card-inner">
                                                    <h5 class="card-title"><em
                                                        class="icon ni ni-users"></em>&nbsp;{% blocktranslate %}Managing your team
                                                        {% endblocktranslate %}</h5>
                                                    <p class="card-text">{% blocktranslate %}Do you need the help of
                                                        another person? Are more people involved? Go to the Team tab and
                                                        send and invitation!
                                                        {% endblocktranslate %}</p><a href="{% url 'project:project_team_index' project.id %}"
                                                        class="btn btn-primary">{% blocktranslate %}Team management
                                                        {% endblocktranslate %}</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!--  Help box start -->
            </div>
        </div>
    </div>
</div>




<div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                <div class="nk-block">
                    <div class="card">
                        <div class="card-aside-wrap">
                            <div class="card-content">
                                <div class="card-inner">

                                    <div class="nk-block-head">
                                        <div class="nk-block-between g-3">
                                            <div class="nk-block-head-content">
                                                <h3 class="nk-block-title page-title">{% trans "Project" %} / <strong
                                                        class="text-primary small">{% trans "Activite" %}</strong></h3>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="timeline">
                                        <ul class="timeline-list">
                                            {% for activity in activities %}
                                            <li class="timeline-item">
                                                <div class="timeline-status bg-primary"></div>
                                                <div class="timeline-date">{{activity.created_at|date:"M d"}} <em
                                                        class="icon ni ni-alarm-alt"></em>
                                                </div>
                                                <div class="timeline-data">
                                                    <h6 class="timeline-title">{{activity.name}}</h6>
                                                    <div class="timeline-des">
                                                        <p>{{activity.description}}</p><span
                                                            class="time mt-1">{{activity.created_at}}</span>
                                                    </div>
                                                </div>
                                            </li>
                                            {% endfor %}
                                        </ul>
                                    </div>

                                    <a href="{% url 'project:project_activity_index' project.id %}"
                                        class="btn btn-outline-primary btn-sm mt-5">
                                        {% trans "Show all activities" %}
                                    </a>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>




{% endblock %}