core/urls.py
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from account.views import Register, RegisterInvite, login_page
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

# for private
import private_storage.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # Media file
    path('private-media/', include(private_storage.urls)),


]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    # AUTH
    path('register', Register, name='register'),
    path('login', login_page, name='login'),
    path('logout/', auth_views.LogoutView.as_view(),
         {'next_page': 'main:start'}, name='logout'),

    # PW reset
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password_reset/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset/password_reset_form.html'), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),


    # Invite
    path('register/invite/<token>', RegisterInvite, name='register_invite'),

    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('order/', include('order.urls')),
    path('client/', include('client.urls')),
    path('project/', include('project.urls')),
    path('notification/', include('notification.urls')),
    path('', include('main.urls')),
    prefix_default_language=False
)


# Error Handling
handler400 = 'main.views.handler_400_view'
handler403 = 'main.views.handler_403_view'
handler404 = 'main.views.handler_404_view'
handler500 = 'main.views.handler_500_view'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from . import views

app_name = 'project'

urlpatterns = [
    path('', views.project_index_view, name='project_index'),
    path('create/<client_id>/<product_id>/<order_id>',
         views.project_create_view, name='project_create'),
    path('create/admin', views.project_create_admin_view,
         name='project_create_admin'),
    path('<int:id>', views.project_detail_view, name='project_detail'),
    path('edit/<int:project_id>', views.project_edit_view, name='project_edit'),
    path('close/<int:project_id>', views.project_close_view, name='project_close'),
    path('archive/<int:project_id>', views.project_archive_view, name='project_archive'),
    path('unarchive/<int:project_id>', views.project_unarchive_view, name='project_unarchive'),


    # Team
    path('<int:project_id>/team', views.project_team_index_view,
         name='project_team_index'),
    path('<int:project_id>/team/create',
         views.project_team_create_view, name='project_team_create'),
    path('<int:project_id>/team-book/create',
         views.project_team_book_create_view, name='project_team_book_create'),
    path('<int:project_id>/team/edit/<int:id>',
         views.project_team_edit_view, name='project_team_edit'),
    path('<int:project_id>/project_team_invite',
         views.project_team_invite_view, name='project_team_invite'),
     path('<int:project_id>/team/invite/delete/<int:id>',
         views.project_team_invite_delete_view, name='project_team_invite_delete'),

     # Document
     
    path('<int:project_id>/document', views.project_document_index_view,
         name='project_document_index'),
    path('<int:project_id>/document/create',
         views.project_document_create_view, name='project_document_create'),
     path('<int:project_id>/document/detail/<int:id>',
         views.project_document_detail_view, name='project_document_detail'),
    path('<int:project_id>/document/edit/<int:id>',
         views.project_document_edit_view, name='project_document_edit'),
     path('<int:project_id>/document/pdf/generate/<int:id>',
         views.GeneratePdf.as_view(), name='project_document_pdf_generate'),
     path('<int:project_id>/document/delete/<int:id>',
         views.project_document_delete_view, name='project_document_delete'),

     

    # Note
    path('<int:project_id>/note', views.project_note_index_view,
         name='project_note_index'),
    path('<int:project_id>/note/create',
         views.project_note_create_view, name='project_note_create'),
    path('<int:project_id>/note/edit/<int:id>',
         views.project_note_edit_view, name='project_note_edit'),
    path('<int:project_id>/note/<int:id>/file/create',
         views.project_note_create_file_view, name='project_note_create_file'),

    # Meet
    path('<int:project_id>/meet', views.project_meet_index_view,
         name='project_meet_index'),
    path('<int:project_id>/meet/create',
         views.project_meet_create_view, name='project_meet_create'),
    path('<int:project_id>/meet/<int:id>',
         views.project_meet_detail_view, name='project_meet_detail'),
    path('<int:project_id>/meet/<int:id>/file/create',
         views.project_meet_create_file_view, name='project_meet_create_file'),
     path('<int:project_id>/meet/<int:id>/edit',
         views.project_meet_edit_view, name='project_meet_edit'),
     path('<int:project_id>/meet/<int:id>/invite',
         views.project_meet_invite_view, name='project_meet_invite'),
    path('<int:project_id>/meet/<int:id>/note/create',
         views.project_note_meet_create_view, name='project_note_meet_create'),
     path('<int:project_id>/meet/delete/<int:id>',
         views.project_meet_delete_view, name='project_meet_delete'),

         
    # Task
    path('<int:project_id>/task', views.project_task_index_view,
         name='project_task_index'),
    path('<int:project_id>/task/<int:id>',
         views.project_task_detail_view, name='project_task_detail'),
    path('<int:project_id>/task/create',
         views.project_task_create_view, name='project_task_create'),
    path('<int:project_id>/task/edit/<int:id>',
         views.project_task_edit_view, name='project_task_edit'),
     path('<int:project_id>/task/responsible/<int:id>',
         views.project_task_responsible_view, name='project_task_responsible'),
    path('<int:project_id>/task/<int:id>/file/create',
         views.project_task_create_file_view, name='project_task_create_file'),
    path('<int:project_id>/task/<int:id>/note/create',
         views.project_note_task_create_view, name='project_note_task_create'),
    path('<int:project_id>/task/archive/<int:id>',
         views.project_task_archive_view, name='project_task_archive'),
     path('<int:project_id>/task/unarchive/<int:id>',
         views.project_task_unarchive_view, name='project_task_unarchive'),

    # Message
    path('<int:project_id>/message', views.project_message_index_view,
         name='project_message_index'),
    path('<int:project_id>/message/users',
         views.project_message_users_view, name='project_message_users'),
    path('<int:project_id>/message/file',
         views.project_message_files_view, name='project_message_files'),

    # File
    path('<int:project_id>/file', views.project_file_index_view,
         name='project_file_index'),
    path('<int:project_id>/file/<int:id>',
         views.project_file_detail_view, name='project_file_detail'),
    path('<int:project_id>/file/create',
         views.project_file_create_view, name='project_file_create'),
    path('<int:project_id>/file/edit/<int:id>',
         views.project_file_edit_view, name='project_file_edit'),
    path('<int:project_id>/file/archive/<int:id>',
         views.project_file_archive_view, name='project_file_archive'),
     path('<int:project_id>/file/unarchive/<int:id>',
         views.project_file_unarchive_view, name='project_file_unarchive'),
    path('<int:project_id>/file/delete/<int:id>',
         views.project_file_delete_view, name='project_file_delete'),


    # Forms
     path('<int:project_id>/form', views.project_form_index_view, name='project_form_index'),
     path('<int:project_id>/form/<int:id>', views.project_form_detail_view, name='project_form_detail'),
     path('<int:project_id>/form/create', views.project_form_create_view, name='project_form_create'),
     # Add users and edit
     path('<int:project_id>/form/duplicate/<int:id>', views.project_form_duplicate_view, name='project_form_duplicate'),
     path('<int:project_id>/form/responsible/<int:id>', views.project_form_responsible_view, name='project_form_responsible'),

    path('<int:project_id>/form/edit/<int:id>', views.project_form_edit_view, name='project_form_edit'),
    path('<int:project_id>/form/edit/participant/<int:id>', views.project_form_edit_participant_view, name='project_form_edit_participant'),
    
    path('forms', views.forms_index_view, name='forms_index'),
    path('<int:project_id>/form/<int:id>/file/create', views.project_form_create_file_view, name='project_form_create_file'),
    path('<int:project_id>/form/<int:id>/note/create', views.project_note_form_create_view, name='project_note_form_create'),

    # Activity
    path('<int:project_id>/activity', views.project_activity_index_view, name='project_activity_index'),
    path('<int:project_id>/lawyer/activity', views.project_lawyer_activity_index_view, name='project_lawyer_activity_index'),

    # Invite
    path('invite', views.invite_index_view, name='invite_index'),
    path('invite/accept/<int:project_id>', views.invite_accept_view, name='invite_accept'),
    path('invite/decline/<int:project_id>', views.invite_decline_view, name='invite_decline'),

    # Lawyer ----------------------------------------------------------------------------------------------

    # Lawyer Overview
    path('<int:project_id>/lawyer', views.project_lawyer_index_view,
         name='project_lawyer_index'),

    # Lawyer - Note
    path('<int:project_id>/lawyer/note',
         views.project_lawyer_note_index_view, name='project_lawyer_note_index'),
    path('<int:project_id>/lawyer/note/create',
         views.project_lawyer_note_create_view, name='project_lawyer_note_create'),
    #path('<int:project_id>/lawyer/note/edit/<int:id>', views.project_lawyer_note_edit_view, name='project_lawyer_note_edit'),
    path('<int:project_id>/lawyer/note/<int:id>/file/create',
         views.project_lawyer_note_create_file_view, name='project_lawyer_note_create_file'),

    # Lawyer - Task
    path('<int:project_id>/lawyer/task',
         views.project_lawyer_task_index_view, name='project_lawyer_task_index'),
    path('<int:project_id>/lawyer/task/<int:id>',
         views.project_lawyer_task_detail_view, name='project_lawyer_task_detail'),
    path('<int:project_id>/lawyer/task/create',
         views.project_lawyer_task_create_view, name='project_lawyer_task_create'),
    path('<int:project_id>/lawyer/task/edit/<int:id>',
         views.project_lawyer_task_edit_view, name='project_lawyer_task_edit'),
    path('<int:project_id>/lawyer/task/<int:id>/file/create',
         views.project_lawyer_task_create_file_view, name='project_lawyer_task_create_file'),
    path('<int:project_id>/lawyer/task/<int:id>/note/create',
         views.project_lawyer_note_task_create_view, name='project_lawyer_note_task_create'),
    path('<int:project_id>/lawyer/task/archive/<int:id>',
         views.project_lawyer_task_archive_view, name='project_lawyer_task_archive'),

    # Lawyer - Message
    path('<int:project_id>/lawyer/message',
         views.project_lawyer_message_index_view, name='project_lawyer_message_index'),
    path('<int:project_id>/lawyer/message/users',
         views.project_lawyer_message_users_view, name='project_lawyer_message_users'),
    path('<int:project_id>/lawyer/message/file',
         views.project_lawyer_message_files_view, name='project_lawyer_message_files'),

    # File

order/models.py
from django.db import models
from shop.models import Product
from client.models import Client
from project.models import Project
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

PAYMENT_METHOD = (
    ('TRANSFER', _('Bank transfer')),
    ('CARD', _('Card')),
)

STATUS = (
    ('PENDING', _('Pending')),
    ('IN_PROGRESS', _('In progress')),
    ('CLOSED', _('Closed')),
    ('ARCHIVED', _('Archived')),
)



class Order(models.Model):
    client = models.ForeignKey(
        Client, related_name='order_client', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_product',
                                on_delete=models.SET_NULL, null=True, blank=True, default=None)
    project = models.ForeignKey(
        Project, on_delete=models.SET_NULL, null=True, blank=True, default=None, related_name='order_project')
    customer = models.CharField(max_length=254, null=True, blank=True)
    name = models.CharField(max_length=254, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)
    comment = models.TextField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    is_read = models.BooleanField(default=False)
    date_start = models.DateTimeField(null=True, blank=True)
    date_end = models.DateTimeField(null=True, blank=True)
    calendar = models.BooleanField(default=False)
    active = models.BooleanField(default=False)
    status = models.CharField(choices=STATUS,max_length=50, default='PENDING')
    lawyer = models.ManyToManyField(
        User, blank=True)  # hozzávonom a rendeléshez
    payment_method = models.CharField(choices=PAYMENT_METHOD,max_length=50, default='TRANSFER')
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('id','-created_at')

    def __str__(self):
        return 'Order {}'.format(self.id)

project/templates/lawyer/task/create.html
{% extends "base_project.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Files
{% endblock %}


{% block content %}

<div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                {% include 'section/project_header.html' %}

                <div class="nk-block">
                    <div class="card">
                        <div class="card-aside-wrap">
                            <div class="card-content">
                                {% include 'section/project_navbar.html' %}
                                {% include 'section/lawyer_navbar.html' %}
                                <div class="card-inner">
                                    <div class="nk-block-head">
                                        <div class="nk-block-between g-3">
                                            <div class="nk-block-head-content">
                                                <h3 class="nk-block-title page-title">Task create</h3>
                                                <div class="nk-block-des text-soft">
                                                    <p>You have total 937 invoices.</p>
                                                </div>
                                            </div>
                                            <div class="nk-block-head-content"><a
                                                    href="{% url 'project:project_lawyer_task_index' project.id %}"
                                                    class="btn btn-outline-light bg-white d-none d-sm-inline-flex"><em
                                                        class="icon ni ni-arrow-left"></em><span>Back</span></a><a
                                                    href="{% url 'project:project_lawyer_task_index' project.id %}"
                                                    class="btn btn-icon btn-outline-light bg-white d-inline-flex d-sm-none"><em
                                                        class="icon ni ni-arrow-left"></em></a></div>
                                        </div>
                                    </div>

                                    <form method="post" autocomplete="off" enctype="multipart/form-data" id="form">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" id="btn-save" class="btn btn-primary">Add task</button>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- content @e -->

<script>
    $(function () {
        $("#id_start_date").datetimepicker({
            format: 'Y-m-d H:i:s'
        });
        $("#id_due_date").datetimepicker({
            format: 'Y-m-d H:i:s'
        });
    });
</script>

<script>
    const form = document.getElementById('form');
    const btnSave = document.getElementById('btn-save')

    form.addEventListener('submit', function () {

        btnSave.innerHTML += ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> <span> </span>'
        btnSave.setAttribute("disabled", "true")
    });
</script>

{% endblock %}

project/templates/lawyer/task/edit.html
{% extends "base_project.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Files
{% endblock %}


{% block content %}

<div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                {% include 'section/project_header.html' %}

                <div class="nk-block">
                    <div class="card">
                        <div class="card-aside-wrap">
                            <div class="card-content">
                                {% include 'section/project_navbar.html' %}
                                {% include 'section/lawyer_navbar.html' %}
                                <div class="card-inner">
                                    <div class="nk-block-head">
                                        <div class="nk-block-between g-3">
                                            <div class="nk-block-head-content">
                                                <h3 class="nk-block-title page-title">Task edit</h3>
                                                <div class="nk-block-des text-soft">
                                                    <p>You have total 937 invoices.</p>
                                                </div>
                                            </div>
                                            <div class="nk-block-head-content"><a
                                                    href="{% url 'project:project_lawyer_task_index' project.id %}"
                                                    class="btn btn-outline-light bg-white d-none d-sm-inline-flex"><em
                                                        class="icon ni ni-arrow-left"></em><span>Back</span></a><a
                                                    href="{% url 'project:project_lawyer_task_index' project.id %}"
                                                    class="btn btn-icon btn-outline-light bg-white d-inline-flex d-sm-none"><em
                                                        class="icon ni ni-arrow-left"></em></a></div>
                                        </div>
                                    </div>

                                    <form method="post" enctype="multipart/form-data" id="form">
                                        {% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" id="btn-save" class="btn btn-primary">Save task</button>
                                    </form>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- content @e -->


<script>
    const form = document.getElementById('form');
    const btnSave = document.getElementById('btn-save')

    form.addEventListener('submit', function () {

        btnSave.innerHTML += ' <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span> <span> </span>'
        btnSave.setAttribute("disabled", "true")
    });
</script>

{% endblock %}

project/templates/lawyer/task/index.html
{% extends "base_project.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Tasks
{% endblock %}


{% block content %}

<div class="nk-content ">
    <div class="container-fluid">
        <div class="nk-content-inner">
            <div class="nk-content-body">
                {% include 'section/project_header.html' %}

                <div class="nk-block">
                    <div class="card">
                        <div class="card-aside-wrap">
                            <div class="card-content">
                                {% include 'section/project_navbar.html' %}
                                {% include 'section/lawyer_navbar.html' %}
                                <div class="card-inner">
                                    <div class="nk-block-head">
                                        <div class="nk-block-between g-3">
                                            <div class="nk-block-head-content">
                                                <h3 class="nk-block-title page-title"><em
                                                        class="icon ni ni-list-check"></em> Tasks</h3>

                                                <div class="nk-block-des text-soft">
                                                    <p>Below can find all the tasks related to tasks for the
                                                        <strong>{{project.name}}</strong>. Click on the task name to
                                                        check the details or create a new task anytime by clicking <a
                                                            href="{% url 'project:project_task_create' project.id %}">here</a>
                                                        or the plus button on the right corner.
                                                    </p>
                                                </div>
                                            </div>
                                            <div class="nk-block-head-content">

                                                <a href="{% url 'project:project_lawyer_task_create' project.id %}"
                                                    class="btn btn-primary"><em
                                                        class="icon ni ni-plus-round-fill"></em><span>Create new
                                                        task</span> </a>

                                            </div>
                                        </div>
                                    </div>

                                    <table class="datatable-init table nk-tb-list nk-tb-ulist">
                                        <thead>
                                            <tr>
                                                <th>Id</th>
                                                <th>Task</th>

                                                <th>Created by</th>

                                                <th>Participants</th>

                                                <th>Notes</th>

                                                <th>Status</th>

                                                <th>Archived?</th>

                                                <th>Due date</th>

                                                <th>Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for task in tasks %}
                                            <tr class="nk-tb-item">
                                                <th scope="row">

                                                    {{task.id}}

                                                </th>
                                                <td>
                                                    {% if task.archived == True %}
                                                    <strong>{{task.name}}</stong>
                                                        {% else %}
                                                        <a
                                                            href="{% url 'project:project_lawyer_task_detail' project_id=project.id id=task.id %}">
                                                            <strong>{{task.name}}</stong>
                                                        </a>
                                                        {% endif %}
                                                </td>

                                                <td>{{task.from_user.first_name}} {{task.from_user.last_name}}</td>

                                                <td>
                                                    {{task.to_user.count}}
                                                </td>

                                                <td>
                                                    {{task.note_task.count}}
                                                </td>


                                                <td>
                                                    <span class="badge badge-pill badge-primary">
                                                        {{task.get_status_display}}
                                                    </span>
                                                </td>

                                                <td>
                                                    {% if task.archived == True %}
                                                    <span class="badge badge-pill badge-danger">
                                                        Yes
                                                    </span>
                                                    {% else %}
                                                    <span class="badge badge-pill badge-secondary">
                                                        No
                                                    </span>
                                                    {% endif %}
                                                </td>

                                                <td>{{task.due_date}}</td>

                                                <td>
                                                    {% if task.archived == False %}
                                                    <a href="{% url 'project:project_lawyer_task_detail' project_id=project.id id=task.id %}"
                                                        class="btn btn-outline-primary btn-sm"><em
                                                            class="icon ni ni-eye"></em>&nbsp; Details</a>
                                                    <a href="{% url 'project:project_lawyer_task_edit' project_id=project.id id=task.id %}"
                                                        class="btn btn-outline-primary btn-sm"><em
                                                            class="icon ni ni-edit"></em>&nbsp; Edit</a>
                                                    <a href="{% url 'project:project_lawyer_task_archive' project_id=project.id id=task.id %}"
                                                        class="btn btn-outline-danger btn-sm"><em
                                                            class="icon ni ni-trash"></em>&nbsp; Archive</a>
                                                    {% else %}

                                                    {% endif %}
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- content @e -->









{% endblock %}