account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.account_index_view, name='account_index'),
    path('edit', views.account_edit_view, name='account_edit'),
    path('template', views.email_template, name='email_template'),
    path('email', views.email_test, name='email_test'),
    
    #path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]

core/urls.py
from django.conf.urls import handler400, handler403, handler404, handler500
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from account.views import Register, RegisterInvite, login_page
from django.contrib.auth import views as auth_views
from django.conf.urls.i18n import i18n_patterns

# for private
import private_storage.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    # Media file
    path('private-media/', include(private_storage.urls)),


]

urlpatterns += i18n_patterns(
    path('i18n/', include('django.conf.urls.i18n')),
    # AUTH
    path('register', Register, name='register'),
    path('login', login_page, name='login'),
    path('logout/', auth_views.LogoutView.as_view(),
         {'next_page': 'main:start'}, name='logout'),

    # PW reset
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_reset/password_change_done.html'), name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(
        template_name='password_reset/password_change.html'), name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='password_reset/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(
        template_name='password_reset/password_reset_form.html'), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='password_reset/password_reset_complete.html'), name='password_reset_complete'),


    # Invite
    path('register/invite/<token>', RegisterInvite, name='register_invite'),

    path('shop/', include('shop.urls')),
    path('account/', include('account.urls')),
    path('order/', include('order.urls')),
    path('client/', include('client.urls')),
    path('project/', include('project.urls')),
    path('notification/', include('notification.urls')),
    path('', include('main.urls')),
    prefix_default_language=False
)


# Error Handling
handler400 = 'main.views.handler_400_view'
handler403 = 'main.views.handler_403_view'
handler404 = 'main.views.handler_404_view'
handler500 = 'main.views.handler_500_view'

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index_view, name='index_view'),
    path('meet', views.meet_index_view, name='meet_index'),
    path('task', views.task_index_view, name='task_index'),
    path('activity', views.activity_index_view,name='activity_index'),
    path('activity/<int:id>', views.activity_detail_view,name='activity_detail'),
    path('page', views.page_index_view,name='page_index'),
    path('page/create', views.page_create_view,name='page_create'),
    path('page/edit/<slug:slug>', views.page_edit_view,name='page_edit'),
    path('page/delete/<slug:slug>', views.page_delete_view,name='page_delete'),
    path('page/<slug:slug>', views.page_detail_view,name='page_detail'),
    #for document
    path('document', views.document_index_view,name='document_index'),
    path('document/create', views.document_create_view,name='document_create'),
    path('document/<int:id>', views.document_detail_view,name='document_detail'),
    path('document/edit/<int:id>', views.document_edit_view,name='document_edit'),
    path('document/delete/<int:id>', views.document_delete_view,name='document_delete'),
    

    #mesibo
    path('mesibo', views.mesibo_view,name='mesibo'),

    #for testing
    path('calendar', views.calendar_index_view, name='calendar_index'),
    path('calendar/create', views.calendar_create_view, name='calendar_create'),

    path('calendly', views.calendly, name='calendly'),
    path('json_calendly_view', views.json_calendly_view, name='json_calendly_view'),

]

notification/urls.py
from django.urls import path
from . import views

app_name = 'notification'


urlpatterns = [
    path('', views.notification_index_view, name='notification_index'),
    path('<int:id>', views.notification_detail_view, name='notification_detail')
    #path('create/', views.notification_create_view, name='notification_create'),
]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('', views.order_index_view, name='order_index'),
    path('create/<product_id>', views.order_create_view, name='order_create'),
    path('<int:id>', views.order_detail_view, name='order_detail'),
    path('edit/<int:id>', views.order_edit_view, name='order_edit'),
    path('delete/<id>', views.order_delete_view, name='order_delete'),

    path('ajax/client', views.order_ajax_client_view, name='order_ajax_client'),
    path('ajax/json_slot', views.json_slot, name='json_slot'),

    path('widget/<product_id>', views.order_widget_view, name='order_widget'),
]

shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.shop_index_view, name='shop_index'),
    path('<slug:slug>', views.shop_detail_view, name='shop_detail'),
    path('category', views.shop_category_view, name='shop_category'),
    path('category/<slug:slug>', views.shop_by_category_view, name='shop_by_category'),
    path('product', views.product_index_view, name='product_index'),
    path('product/<int:id>', views.product_detail_view, name='product_detail'),
    path('product/create', views.product_create_view, name='product_create'),
    path('product/edit/<int:id>', views.product_edit_view, name='product_edit'),
    path('product/delete/<int:id>', views.product_delete_view, name='product_delete'),
    
]

order/forms.py
from django import forms
from .models import Order
from shop.models import Product
from crispy_forms.helper import FormHelper


class OrderCreateForm(forms.ModelForm):
    date_start = forms.CharField(widget=forms.HiddenInput(), required=False)
    time_start = forms.CharField(widget=forms.HiddenInput(), required=False)
    duration = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Order
        fields = ['client', 'payment_method', 'date_start', 'time_start', 'duration', 'comment']
        exclude = ['quantity', 'paid', 'price', 'active', 'product']
       


class OrderEditForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['paid']
        exclude = ['client', 'quantity', 'price', 'product', 'active']

order/views.py
from collections import Counter
import datetime as dt
from datetime import datetime, timedelta, time
from django import forms
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import redirect, render, get_object_or_404
from notification.models import Notification
from order.forms import OrderCreateForm, OrderEditForm
from client.forms import ClientCreateForm
from order.models import Order
from project.models import Activity, Project, ProjectForm, ProjectFormDefault, Task, TaskDefault, Team
from shop.models import Product
from client.models import Client
from django.contrib.auth.models import User
from django.contrib import messages
from django.forms.models import model_to_dict
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from smtplib import SMTPException
from django.template.loader import render_to_string
from core.utils import SignalSystem
from django.contrib.sites.shortcuts import get_current_site #domaint innen szerzem meg
from datetime import datetime, timedelta
from django.utils.translation import ugettext_lazy as _


@login_required
def order_index_view(request):
    context = {}
    user = request.user
    if user.profile.user_role == 1 or user.profile.user_role == 2:
        orders = Order.objects.filter(client__user=user)
        context = {}
        context['orders'] = orders
        return render(request, 'order/my_order.html', context)
    if user.profile.user_role == 3:
        orders = Order.objects.all().order_by('-id')
        context['orders'] = orders
        return render(request, 'order/index.html', context)


@login_required
def order_create_view(request, product_id):
    user = request.user
    now = datetime.now()
    product = Product.objects.filter(id=product_id).first()
    context = {}
    # speciális számozáshoz a kóód
    raw_today = datetime.today()
    str_today = str(raw_today.strftime("%y-%m-%d"))
    today = str_today.replace('-', '')

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            payment_method = form.cleaned_data.get('payment_method')  #payment_method
            client_id = form.cleaned_data.get('client')
            raw_start_date = form.cleaned_data.get(
                'date_start')  # get only date i.e. 2010-10-10
            duration = form.cleaned_data.get('duration')
            raw_start_time = form.cleaned_data.get(
                'time_start')  # get only time i.e. 10:10

            client = Client.objects.filter(name=client_id).first()

            # start_date + start_time
            if product.calendar == True:
                date_start_str = str(raw_start_date + ' ' + raw_start_time)
                date_start = datetime.strptime(
                    date_start_str, '%Y-%m-%d %H:%M')

                if date_start:
                    date__end = date_start + timedelta(minutes=int(duration))
                    date_end = date__end.strftime('%Y-%m-%d %H:%M')
            else:
                date_start = None #datetime.now()
                date_end = None #datetime.now()

            obj = form.save(commit=False)
            obj.user = user
            # megnézem hogy adott termék calnedaros e. Fontos ez mert ez alapján könnyne tudok szűrni mikor officos hozza létre az időpontot
            if product.calendar == True:
                obj.calendar = True
            else:
                obj.calendar = False
            obj.price = product.price

            obj.date_start = date_start  # ha van meet ip
            if date_start:
                obj.date_end = date_end  # ha van meet ip
            
            obj.price = product.price
            obj.product = product
            obj.name = product
            obj.customer = client
            obj.save()

            # Variable for create project
            order_id = obj.id
            order = Order.objects.filter(id=order_id).first()
            # speckós azonostióó
            project_name = f'{product.name} - ({today}-{order_id}-1)'

            # Automate create project
            project = Project.objects.create(
                name=project_name, description='', client=client, order_number=order_id)
            if(project):
                print('A project létrejött')
                Order.objects.filter(id=order_id).update(project=project)
            else:
                print('A project nem jött létre')

            # Add Officer to team
            create_office = Team.objects.create(
                email='info@legisly.com', project=project, role=3, staff=True, active=True, is_removable=False)
            if create_office:
                print('létrehozva')
            else:
                print('Nem lett hozzáadva az admin')

            # Add Client to team
            create_client = Team.objects.create(
                email=client.user.email, role=2, customer=True, user=client.user, project=project, active=True, is_removable=False)
            if create_client:
                Order.objects.filter(id=order_id).update(active=True)
                print('létrehozva')
            else:
                print('Nem lett hozzáadva a client')

            # Form search and create
            default_form = ProjectFormDefault.objects.filter(
                product=product, default_form=True)  #--> ez akkor jön képbe ha alapértelmezetten bnet vna a pipa
            for default in default_form:
                obj = ProjectFormDefault.objects.get(id=default.id)
                add_day = int(obj.start_date_plus_day)
                due_date = now + timedelta(days=add_day)
                ProjectForm.objects.create(name=f'#{order_id} - {obj.name} form - {project.name}',
                                           form_schema=obj.default_schema, form_meta=obj.default_meta, project=project, responsible_user=user, start_date=now,multiple=obj.multiple,question=obj.question,button_text = obj.button_text,due_date=due_date)
                # majd itt kell hozzáadni hogy many to many hozzáadja a team typot

            # Default task to project
            default_task = TaskDefault.objects.filter(product=product)
            for default in default_task:
                obj = TaskDefault.objects.get(id=default.id)
                add_day = int(obj.start_date_plus_day)
                due_date = now + timedelta(days=add_day)
                t = Task.objects.create(
                    name=f'{obj.name} - default', description=obj.description, project=project, start_date=now, due_date=due_date, responsible_user=user, from_user=user)
                t.to_user.add(user)

            try:
                # Activity
                Activity.objects.create(project=project, name=_('Project is created'),
                                        description=f'{_("The project is created. The project name:")} {project.name}.')
                Activity.objects.create(project=project, name=_('Team created'),
                                        description=f'{_("The client added to")} {project.name}.')
            except:
                # TODO: error
                pass

            # send email with task and others
            task_qs = Task.objects.filter(project = project)
            form_qs = ProjectForm.objects.filter(project = project)
            context['DOMAIN'] = get_current_site(request)
            context['client'] = client
            context['project'] = project
            context['task_qs'] = task_qs
            context['form_qs'] = form_qs
            context['user_obj'] = user
            context['product'] = product
            context['order'] = order
            #user.email
            SignalSystem.email(user.email, _("Your case is started!"), 'email_project_start.html', context)

            # payment_method email
            if payment_method == 'TRANSFER':
                SignalSystem.email(user.email, _("Thank you for your order!"), 'email_order_bank_transfer.html', context)
            elif payment_method == 'CARD':
                SignalSystem.email(user.email, _("Thank you for your order!"), 'email_order_card.html', context)
  
            messages.success(request, _('Order created!'))
            if user.profile.user_role == 1:
                return redirect('project:project_index')
            else:
                return redirect('order:order_index')
    else:
        form = OrderCreateForm()
        form.fields['client'] = forms.ModelChoiceField(
            Client.objects.filter(user=user).exclude(archived=True), label=_('Choose client'))
        

    return render(request, 'order/create.html', {'form': form, 'product': product, 'product_id': product_id})


@login_required
def order_detail_view(request, id):
    order = Order.objects.filter(id=id).first()
    context = {}
    context['order'] = order
    return render(request, 'order/detail.html', context)


def order_edit_view(request, id):
    order = Order.objects.filter(id=id).first()

    if request.method == 'POST':
        form = OrderEditForm(request.POST, instance=order)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.save()
            messages.success(request, _('Saved'))

            return redirect('order:order_index')
        else:
            print('Hibás')
    else:
        form = OrderEditForm(instance=order)
    return render(request, 'order/edit.html', {'form': form, 'order': order})

# Csak admin


def order_delete_view(request, id):
    user = request.user
    order = Order.objects.filter(id=id).first()
    # Notify
    Notification.objects.create_notification(
        user, order.client.user, order.client.user, 'Megrendelés törlése', 'INFO', f'A megrendelés törölve - {order.client}')
    order.delete()
    messages.success(request, _('Kliens siekresen törölve'))
    return redirect('order:order_index')


def time_slots(start_time, end_time, duration):
    t = start_time
    while t <= end_time:

order/templates/section/sidebar_admin.html
{% load static %}
 <!-- sidebar @s -->
 <div class="nk-sidebar nk-sidebar-fixed is-light " data-content="sidebarMenu">
    <div class="nk-sidebar-element nk-sidebar-head">
        <div class="nk-sidebar-brand">
            <a href="html/index.html" class="logo-link nk-sidebar-logo">
                <img class="logo-light logo-img" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo">
                <img class="logo-dark logo-img" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo-dark">
                <img class="logo-small logo-img logo-img-small" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo-small">
            </a>
        </div>
        <div class="nk-menu-trigger mr-n2">
            <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
            <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
        </div>
    </div><!-- .nk-sidebar-element -->
    <div class="nk-sidebar-element">
        <div class="nk-sidebar-content">
            <div class="nk-sidebar-menu" data-simplebar>
                <ul class="nk-menu">
                    <li class="nk-menu-heading">
                        <h6 class="overline-title text-primary-alt">Webshop</h6>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'shop:shop_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-bag"></em></span>
                            <span class="nk-menu-text">Products</span><span class="nk-menu-badge">NEW</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'shop:shop_category' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-grid-alt-fill"></em></span>
                            <span class="nk-menu-text">Category</span>
                        </a>
                    </li>
                    <li class="nk-menu-item">
                        <a href="{% url 'order:order_my_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-book-read"></em></span>
                            <span class="nk-menu-text">Orders</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-heading">
                        <h6 class="overline-title text-primary-alt">Dashboards</h6>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-home"></em></span>
                            <span class="nk-menu-text">Overview</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-mail"></em></span>
                            <span class="nk-menu-text">Messages</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                  
                
                 
                   
                   
                    <li class="nk-menu-heading">
                        <h6 class="overline-title text-primary-alt">Account</h6>
                    </li><!-- .nk-menu-heading -->
                    <li class="nk-menu-item">
                        <a href="{% url 'account:account_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-user"></em></span>
                            <span class="nk-menu-text">My profile</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="html/index.html" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-question"></em></span>
                            <span class="nk-menu-text">Help</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                 
                </ul><!-- .nk-menu -->
            </div><!-- .nk-sidebar-menu -->
        </div><!-- .nk-sidebar-content -->
    </div><!-- .nk-sidebar-element -->
</div>
<!-- sidebar @e -->

order/templates/section/sidebar_anonymus.html
{% load static %}
 <!-- sidebar @s -->
 <div class="nk-sidebar nk-sidebar-fixed is-light " data-content="sidebarMenu">
    <div class="nk-sidebar-element nk-sidebar-head">
        <div class="nk-sidebar-brand">
            <a href="html/index.html" class="logo-link nk-sidebar-logo">
                <img class="logo-light logo-img" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo">
                <img class="logo-dark logo-img" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo-dark">
                <img class="logo-small logo-img logo-img-small" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo-small">
            </a>
        </div>
        <div class="nk-menu-trigger mr-n2">
            <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
            <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
        </div>
    </div><!-- .nk-sidebar-element -->
    <div class="nk-sidebar-element">
        <div class="nk-sidebar-content">
            <div class="nk-sidebar-menu" data-simplebar>
                <ul class="nk-menu">
                    <li class="nk-menu-heading">
                        <h6 class="overline-title text-primary-alt">Webshop</h6>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'shop:shop_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-bag"></em></span>
                            <span class="nk-menu-text">Products</span><span class="nk-menu-badge">NEW</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'shop:shop_category' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-grid-alt-fill"></em></span>
                            <span class="nk-menu-text">Category</span>
                        </a>
                    </li>
                   
                </ul><!-- .nk-menu -->
            </div><!-- .nk-sidebar-menu -->
        </div><!-- .nk-sidebar-content -->
    </div><!-- .nk-sidebar-element -->
</div>
<!-- sidebar @e -->

order/templates/section/sidebar_user.html
{% load static %}
 <!-- sidebar @s -->
 <div class="nk-sidebar nk-sidebar-fixed is-light " data-content="sidebarMenu">
    <div class="nk-sidebar-element nk-sidebar-head">
        <div class="nk-sidebar-brand">
            <a href="html/index.html" class="logo-link nk-sidebar-logo">
                <img class="logo-light logo-img" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo">
                <img class="logo-dark logo-img" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo-dark">
                <img class="logo-small logo-img logo-img-small" src="{% static '/assets/auth/images/logo.png' %}" srcset="{% static '/assets/auth/images/logo.png' %} 2x" alt="logo-small">
            </a>
        </div>
        <div class="nk-menu-trigger mr-n2">
            <a href="#" class="nk-nav-toggle nk-quick-nav-icon d-xl-none" data-target="sidebarMenu"><em class="icon ni ni-arrow-left"></em></a>
            <a href="#" class="nk-nav-compact nk-quick-nav-icon d-none d-xl-inline-flex" data-target="sidebarMenu"><em class="icon ni ni-menu"></em></a>
        </div>
    </div><!-- .nk-sidebar-element -->
    <div class="nk-sidebar-element">
        <div class="nk-sidebar-content">
            <div class="nk-sidebar-menu" data-simplebar>
                <ul class="nk-menu">
                    <li class="nk-menu-heading">
                        <h6 class="overline-title text-primary-alt">Webshop</h6>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'shop:shop_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-bag"></em></span>
                            <span class="nk-menu-text">Products</span><span class="nk-menu-badge">NEW</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'shop:shop_category' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-grid-alt-fill"></em></span>
                            <span class="nk-menu-text">Category</span>
                        </a>
                    </li>
                    <li class="nk-menu-heading">
                        <h6 class="overline-title text-primary-alt">Dashboards</h6>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-home"></em></span>
                            <span class="nk-menu-text">Overview</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-mail"></em></span>
                            <span class="nk-menu-text">Messages</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'client:client_my_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-users"></em></span>
                            <span class="nk-menu-text">Clients</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'project:project_my_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-activity-round-fill"></em></span>
                            <span class="nk-menu-text">Projects</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'main:meet_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-video"></em></span>
                            <span class="nk-menu-text">Next meets</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'main:meet_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-video"></em></span>
                            <span class="nk-menu-text">Tasks</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="{% url 'main:meet_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-video"></em></span>
                            <span class="nk-menu-text">Invites</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="html/index.html" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-calendar"></em></span>
                            <span class="nk-menu-text">Calendar</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                   
                    <li class="nk-menu-heading">
                        <h6 class="overline-title text-primary-alt">Account</h6>
                    </li><!-- .nk-menu-heading -->
                    <li class="nk-menu-item">
                        <a href="{% url 'account:account_index' %}" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-user"></em></span>
                            <span class="nk-menu-text">My profile</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                    <li class="nk-menu-item">
                        <a href="html/index.html" class="nk-menu-link">
                            <span class="nk-menu-icon"><em class="icon ni ni-question"></em></span>
                            <span class="nk-menu-text">Help</span>
                        </a>
                    </li><!-- .nk-menu-item -->
                 
                </ul><!-- .nk-menu -->
            </div><!-- .nk-sidebar-menu -->
        </div><!-- .nk-sidebar-content -->
    </div><!-- .nk-sidebar-element -->
</div>
<!-- sidebar @e -->